In [1]:
import jax
import jax.numpy as jnp
import env
import agent

An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.


# K-armed bandit

In [ ]:
true_mu = jnp.array([-1.0, -0.5, 0.0, 0.3, 0.6, 0.9, 1.2, 1.0, 0.4, -0.8])
t = 0
n_steps_a = jnp.zeros(10)
key = jax.random.key(0)

#I should vmap through environment to create baseline. But then what? hmmmm. what function would i even pass into my environment
#This is (t, N, Q)
state = (  t,  jnp.zeros(10), jnp.zeros(10),key)
c = 0.5

def pick_every_lever_innit(state, filler):
     state,n = env.k_slots(agent.pick_every_lever, state, true_mu)
     return state,n

state, n = jax.lax.scan(pick_every_lever_innit,state, length=len(true_mu))


def UCB_bandit(state, filler):
     state, n = env.k_slots(agent.UCB_agent, state, true_mu)
     return state, n

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
